version: '3.7'
services:
    database:
        image: 'mysql:8.0'
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: always
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '4306:3306'
        volumes:
            - ./mysql:/var/lib/mysql

    php-apache:
        build: php
        ports:
            - "8000:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always

    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            - database
        ports:
            - 8080:80
        environment:
            PMA_HOST: database
